name: CI/CD Review Filmes

on:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build da imagem Docker
        run: docker build -t tiagoferreira97/review-filmes-web:${{ github.sha }} -f ./02-review/src/Review-Filmes.Web/Dockerfile ./02-review/src

      - name: Push da imagem
        run: docker push tiagoferreira97/review-filmes-web:${{ github.sha }}

      - name: Atualizar imagem no manifesto
        run: |
          sed -i "s|image: tiagoferreira97/review-filmes-web:.*|image: tiagoferreira97/review-filmes-web:${{ github.sha }}|" ./02-review/k8s/deployment.yaml

      - name: Upload do manifesto atualizado
        uses: actions/upload-artifact@v4
        with:
          name: k8s-manifest
          path: ./02-review/k8s/

  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Baixar manifestos atualizados
        uses: actions/download-artifact@v4
        with:
          name: k8s-manifest
          path: ./02-review/k8s/

      - name: Configurar kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Deploy no Kubernetes
        run: kubectl apply -f ./02-review/k8s/
